FROM almalinux:9
ADD https://raw.githubusercontent.com/daws-86s/notes/refs/heads/main/session-01.txt /tmp/notes.txt
ADD sample-1.tar /tmp/
# CMD ["echo", "Hello, world!"] # echo runs, prints the message, finishes instantly, and the container stops.
CMD ["sleep", "infinity"]